FROM golang:alpine
# can golang without cgo, python, ...

# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools


ENV GOFLAGS="-mod=vendor"
ENV CGO_ENABLED=0

ADD ./examples /tests
WORKDIR /tests

CMD ["go", "test", "-v", "./main_test.go"]
#ENTRYPOINT ["/bin/sh"]

#RUN go build examples -o /app
